name: Singularity Build (native)
on: 
  push:
    # Edit the branches here if you want to change deploy behavior
    branches:
      - main
      - master

  # Do the builds on all pull requests (to test them)
  pull_request: []

jobs:

    name: Check ${{ matrix.changed_file }}
    steps:
      - uses: actions/checkout@v2
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      - name: Build Container
        run: |
         ls 
         sudo -E singularity build container.sif ${{ matrix.changed_file }}
         tag=$(echo "${recipe/Singularity\./}")
         if [ "$tag" == "Singularity" ]; then
           tag=latest
         fi
         # Build the container and name by tag
         echo "Tag is $tag."
         echo "tag=$tag" >> $GITHUB_ENV

      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        run: |         
             echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
             singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
